#!/bin/bash

#setup argument
psql_host=$1
port=$2
db_name=$3
user_name=$4
password=$5

specs=`lscpu`

get_hostname(){
 	hostname=$(hostname -f)
}

get_cpu_number(){
	cpu_number=$(echo "$specs" | egrep "^CPU\(s\):" | awk '{print $2}' | xargs)
}

get_specs(){
	pattern=$1
	value=$(echo "$specs" | egrep "$pattern" | awk -F ':' '{print $2}' |xargs)
	echo "value=$value"
}

get_cpu_architecture(){
	get_specs "Architecture"
	cpu_architecture=$value
}

get_cpu_model(){
	get_specs "Model name:"
	cpu_model=$value
}

get_cpu_mhz(){
	get_specs "CPU MHz:"
	cpu_mhz=$value
}

get_L2_cache(){
	get_specs "L2 cache:"
	L2_cache=$(echo $value | sed s'/K//')
}

#Step 1: Parse data and setup variable
get_hostname
get_cpu_number
get_cpu_architecture
get_cpu_model
get_cpu_mhz
get_L2_cache
total_mem=$(cat /proc/meminfo | head -1 | awk '{print $2}' | xargs)
timestamp=$(date "+%Y-%m-%d %T") 

#spre 2: Construct Insert statement
insert_stmt=$(cat << END
INSERT INTO host_info(hostname, cpu_number, cpu_architecture, cpu_model, cpu_mhz, l2_cache, total_mem, "timestamp") VALUES ('${hostname}',${cpu_number},'${cpu_architecture}','${cpu_model}',${cpu_mhz},${L2_cache},${total_mem},'${timestamp}');
END
)
echo $insert_stmt

#step 3:Execute INSERT Statemetn
export PGPASSWORD=$password
psql -h $psql_host -p $port -U $user_name -d $db_name -c "$insert_stmt"
sleep 1

#step4: save host_id generated by PSQL table to local file 
host_id=`psql -h localhost -U postgres host_agent -c "select id from host_info where hostname='${hostname}'" | tail -3 | head -1 |xargs `
echo $host_id > ~/host_id
cat ~/host_id
